### ISSUE TITLE
[CI] e2e test community growth. how to do sudo on dev parachain?

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#109]
we should do the same integration like we do for encointer-node

Difficulty:
* there is no sudo pallet, so `new-community` and `next-phase` won't work like they do now (`faucet` is fine because Alice is endowed in the dev setup. but on live rococo we'll need to initialize Alice with a teleport)

# solution 1

add new runtime `encointer-dev-runtime` which is exactly the same as `encointer-runtime` plus `sudo` pallet

:-1:  this means more maintenance and potential for confusion. Moreover, we're not really guaranteed to be testing what we're deploying

# solution 2

make helper scripts more flexible and sudo through relaychain XCM

* if cli parameter `--relay-chain-ws-port <port>` is present, use relaychain sudo 

the privileged function that should be executed: take encoded call from here:
![image](https://user-images.githubusercontent.com/10366175/160786581-d5f72cda-8b73-459f-a9c5-db4cb1ce0037.png)

and execute a sudo call on relaychain:
![image](https://user-images.githubusercontent.com/10366175/160786781-9157ea8e-7ab6-4236-aa4f-d0476bb07759.png)

# solution 3

use council/collective for `new-community` and `next_phase` calls.

upside: we're really testing what we'd do on the parachain itself

In general , we'd need 5 extrinsics for that
* `collective.propose(encointer_scheduler.netx_phase`, ...)` and read proposal hash from events
* 3x `collective.vote(<proposal-hash>)` by Alice, Bob, Charlie
* `collective.close(<proposal-hash>, index ....)`

But if council has only one member, every proposal will be executed directly, without voting, so we just need to replace
```
sudo.sudo()
```
with
```
collective.propose()
```
in this case.

**Comment by gilescope** [comment]
For statemine/t testing we take the second approach of cherrypicking this commit in the polkadot repo:

git cherry-pick 755a4b69c94ba75618080c76d25133b11c1d58db

That adds in a sudo to the relay chain. Personally I'd like an add-sudo feature but I think people are against even the perception that there might be a sudo pallet on the relay chain so I think that would get vetoed.

**Comment by brenzi** [comment]
Thank you @gilescope, that is helpful for testing not rococo-local but really kusama/polkadot. Didn't know about this.
However, this issue is about permissioned calls on the parachain, not relaychain. Your solution would go in the direction of mentioned **solution 1**, which I do not prefer as it modifies the runtime

**Comment by brenzi** [comment]
It shall be solution 3 with a single councillor on the -dev chain

**Comment by brenzi** [comment]
https://github.com/encointer/encointer-node/pull/197

solved
