### ISSUE TITLE
Is the randomness source secure enough?

### ISSUE THREAD

**Issue by gilescope** [encointer/encointer-parachain#112]
https://docs.substrate.io/v3/runtime/randomness/ says:

"The first implementation provided by Substrate is the [Randomness Collective Flip Pallet](https://docs.substrate.io/rustdocs/latest/pallet_randomness_collective_flip/index.html). This pallet is based on collective coin flipping. It is quite performant, but not very secure. This pallet should be used only when testing randomness-consuming pallets, not it production."

Is there a plan to move to something more secure than randomness collective flip or alternatively is there a good justification as to why it is adequate for this use case?

**Comment by brenzi** [comment]
The concern about randomness is legit of course. Here the reasoning why we so far considered "simple" randomness to be sufficiently secure:

Randomness is used to assign meetups for a ceremony. The randomness is therefore only used globally for intrinsics, never on individual extrinsic level. There is, however,  a chance of provoking favorable assignments for certain collusion attacks on the protocol. These attacks are considered very complex and there isn't really a lot to gain by taking it out.

By the time such an attack would pay out, we will have migrated to a TEE-based layer 2 anyway for scalability reasons - according to plan (Conceptually like [testnet Cantillon](https://book.encointer.org/testnet-cantillon.html), which would provide its own randomness)

The layer1 remedy would be to use Babe consensus and its provable random source. Our parachain currently uses Aura and changing that is left for later -if at all. (is there a parachain which uses Babe for randomness already? No parachain in cumulus, nor Acala, nor Moonbeam are currently using Babe)
