### ISSUE TITLE
upgrade encointer-kusama collators to 1.0.1

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#123]
Our runtime upgrade got passed. now we'll need to upgrade collators to benefit from the new rpc and polkadot upgrades

**Comment by mosonyi** [comment]
Upgraded, used chain=encointer-kusama.
However in telemetry I cannot see the new Encointer on Kusama name
![image](https://user-images.githubusercontent.com/6170620/163840560-d7910eb6-a789-4898-bd46-5d2b22fef755.png)
