### ISSUE TITLE
[rococo] js/apps unable to decode block with encointer extrinsics

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#127]
If a block has encointer extrinsics in there, the block can't be decoded (in this case, fees were paid with CC!) 

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.api.encointer.org#/explorer/query/0xfb56d3ad3451d25a213a90c14fffa06cfedd177389f1fa697bc2786de369cf8f

`Unable to retrieve the specified block details. createType(SignedBlock):: Struct: failed on block: {"header":"Header","extrinsics":"Vec<Extrinsic>"}:: Struct: failed on extrinsics: Vec<Extrinsic>:: createType(ExtrinsicV4):: createType(Call):: findMetaCall: Unable to find Call with index [52, 171]/[52,171]`

the cermonies pallet has index 61, balances 63, there is no pallet with index 52! 
https://github.com/encointer/encointer-parachain/blob/cc82e90db6790030db1929bb6b7230b735ea4191/polkadot-parachains/encointer-runtime/src/lib.rs#L748-L755

**Comment by brenzi** [comment]
@clangenb I suspect this is related to the signedExtension. Seems js/apps can't decode that. Can we fix this easily?

**Comment by clangenb** [comment]
Yes, this is probably because the `assetId` of the signed extension is not null then. While implementing cc-fees on app side, I noticed that polkadot-js/app does not generate the signed extensions on the fly; It has a predefined set, which uses `Option<Number>` for the `OnChargeAssetTxPayment` signed extension.

Hence, as long as it is `None` it decodes just fine.

Since, `polkadot-js/apps` does no longer  allow extending the metadata, I don't know how to fix that. I'll make an issue there.

**Comment by clangenb** [comment]
Answer from Jaco: Not yet supported, but will be in the future.

**Comment by clangenb** [comment]
This is how we solved it on the client side in the app for polkadot-js:

```
const api = await ApiPromise.create({
  ...options({
    types: configOverride.types !== null ? configOverride.types : {}
  }),
  signedExtensions: {
    ChargeAssetTxPayment: {
      extrinsic: {
        tip: 'Compact<Balance>',
        assetId: 'Option<CommunityIdentifier>'
      },
      payload: {}
    }
  },
  provider: provider
});
```

**Comment by clangenb** [comment]
I don't know why we did not know this before, but we can fix the decoding issue by supplying the signed extensions into that file at polkadot-js/apps: https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/encointer-para.ts

**Comment by clangenb** [comment]
I don't understand, the polkadot-js/apps includes our fix, but it can't decode the block still. Try to decode the following block: 0xa3803eae4c029e7d2e30dec91b6af16294e0b82aea9d5b805e0fa6f6564bbd7b.

Do you have any idea @pifragile ?

**Comment by pifragile** [comment]
@clangenb i cannot see the issue, [decoding works](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama.api.encointer.org#/explorer/query/0xa3803eae4c029e7d2e30dec91b6af16294e0b82aea9d5b805e0fa6f6564bbd7b)

**Comment by clangenb** [comment]
Indeed, it was a browser caching issue! Very cool!
