### ISSUE TITLE
common good lease renewal

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#143]
example from statemine:
https://kusama.polkassembly.io/post/1735

filed ~50 days prior to lease expiry. js/apps now says LP 22-23. the proposal is for 16 LP starting with 24

Encointer lease is up to and including LP 25

We aim at extending by 8 LP's, starting with LP 26

LP 26 starts around Jan 15th 2023

**Comment by clangenb** [comment]
This has been done.
