### ISSUE TITLE
Fix polkadot-js/apps signed extensions types for the encointer-parachain.

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-parachain#147]
We can fix the decoding issues for polkadot-js/apps by supplying custom types for our encointer-para.

- [x] Create fork of polkadot-js/apps: https://github.com/polkadot-js/apps
- [ ] Update https://github.com/encointer/polkadot-js-apps/blob/master/packages/apps-config/src/api/spec/encointer-para.ts
    - [ ] Add two `minMax` sections (the numbers in the `minMax` interval correspond to spec_versions):
        - [ ] `minMax`: [0, n], where n is the spec version before we added the custom signed extension. In this section, we only add the types. Note: double-check the types, with what we currently have in encointer-js.
        - [ ] `minMax`: [n, undefined] add the types that are currently used, and add the signed extension as below:
- [ ] test with a local instance of polkadot-js if this block from #127 can be decoded.
- [ ]  when it works, we can do the more elegant way and add the overrideBundle to encointer-js, and simply import it in the polkadot-js/apps as an npm package. Example: https://github.com/polkadot-js/apps/blob/7da84a012992cd07cff064988d2c08cf6c265fd3/packages/apps-config/src/api/spec/acala.ts#L4
- [ ] Import the package into the polkadot-js/apps fork. And test again if it works.
- [ ] Make upstream PR to polkadot-js apps.
        
        
```ts
const definitions: OverrideBundleDefinition = {
    types: [{
            // on all versions
            minmax: [0, undefined],
            types: {
                Address: "AccountId",
                LookupSource: "AccountId",
                // other types///
            },
            signedExtensions: {
                ChargeAssetTxPayment: {
                    extrinsic: {
                        tip: "Compact<Balance>",
                        assetId: "Option<CommunityIdentifier>"
                    },
                    payload: {}
                }
            }
        },
    ],
};
```

Caveat: Depending on how we changed the types, we might need more `minMax` sections.

Note: Maybe we can add another `minMax` section with [m, undefined], where m is the spec version, where we introduced the self-descriptive metadata v14. In this section we can leave the types empty, and only add the signed extensions.

**Comment by brenzi** [comment]
solved by https://github.com/polkadot-js/apps/pull/8425
