### ISSUE TITLE
Adding sr-tools version in the release note.

### ISSUE THREAD

**Issue by cheme** [encointer/encointer-parachain#159]
Would be good if the sr-tools image version will be specified in the release note (for instance to check 1.3.2 runtime hash of recent referendum I just did build with the latest sr-tools v1.64.0 image, but in a few month the latest sr-tools version would not be the same one and the information would be very useful).
For instance in release note for polakdot runtime there is `The runtimes have been built using [srtool v0.9.23](https://github.com/paritytech/srtool) and rustc 1.64.0 (a55dd71d5 2022-09-19).` written in the [release note](https://github.com/paritytech/polkadot/releases/tag/v0.9.33)

**Comment by brenzi** [comment]
thank you @cheme. we now build with stable, I guess that's even better

**Comment by cheme** [comment]
Problem with stable is that in a few years/month, it will be difficult to find the right version of sr-tools and build (in case someone don't trust some consensus at some point or believe noone check correctly the building process of a runtime, the only way for him to assert it is to build it again).

**Comment by clangenb** [comment]
I agree with @cheme here. Building with stable does not fix the reproducibility issue. It is noted in the logs of GitHub actions, but those logs only have a limited lifetime.
