### ISSUE TITLE
Typedef in this repo is outdated for gesell 0.4.0, should we update it?

### ISSUE THREAD

**Issue by anizeani** [encointer/encointer-parachain#16]
https://github.com/encointer/encointer-parachain/blob/master/typedefs.json
This typedef is missing for example the bazaartype definition. 
Should we update the file or is this file anyway not necessary anymore?

**Comment by clangenb** [comment]
It is necessary and should be updated. Please do that.

**Comment by brenzi** [comment]
since https://github.com/paritytech/substrate/commit/ba153b9ae050eda022f002d74d76f98d1e339a81
we don't need to maintain a type-registry anymore. 

We should rather upgrade and use that
