### ISSUE TITLE
benchmark encointer-parachain-runtime

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#21]
depends on: https://github.com/encointer/pallets/issues/56

check: https://github.com/integritee-network/parachain/commit/536374facdefe5b1fd8d72b0fdf0e03a4fde8700

**Comment by clangenb** [comment]
The benchmarking pipeline has been implemented in
* https://github.com/encointer/encointer-parachain/pull/55

Hence, we only need to run the benchmark again after we have made the encointer-pallets compatible with v0.9.12 and reintroduced them into the encointer-runtime.

**Comment by clangenb** [comment]
Steps:
* bump encointer-pallets to get benchmarks
* Run the steps defined here https://github.com/encointer/encointer-node#benchmarking,  which also includes adding the script `run_benchmarks.sh` to the repository.
