### ISSUE TITLE
westend testing

### ISSUE THREAD

**Issue by brenzi** [encointer/encointer-parachain#26]
(or maybe rococo-reloaded by then?)

1. launch "shell" (#19 ) runtime
2. up-downward transfer relaychain native token
3. verify fee collection to treasury (no burn!)
2. upgrade code to full encointer runtime
3. test bot-community growth

do not yet test sybil-defense as we won't have a matching parachain for that. collaborations will be needed for this

**Comment by brenzi** [comment]
we launched on westend successfully, but the relaychain needed to be 0.9.13-rc1 for the first blocks to be produced
can't test more as we need to be a trusted teleporter to test other stuff

**Comment by mosonyi** [comment]
We already moved from westend to rococo. This can be closed.
