### ISSUE TITLE
Verify XCM config to be secure and sensible

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-parachain#44]
We have a working xcm config for facilitating downwards/upwards token tx. However, we should:

- [ ] We should double-check if the current config is secure.
- [ ] Find out why our parachain advertises only XcmV1 as protocol. As I read our codebase, it should advertise v2. As it only advertises v1, we need to overwrite the default xcm-version for our parachain with a root call.

**Comment by brenzi** [comment]
we now have 1:1 statemine config
