### ISSUE TITLE
[polkadot-launch] can't launch relay-chain live configs

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-parachain#47]
For some reason I can't launch live chains (westend, kusama, rococo without any suffix) with polkadot-launch. All other chain-specs work.

* Polkadot-launch: https://github.com/paritytech/polkadot-launch/commit/6f66f9f0b75fafbf650a79f9aa5d3fdbda28dcda
* Polkadot bin release-v0.9.12 branch (v0.9.10, did not work either): https://github.com/paritytech/polkadot/commit/5feed981cf0fe671447eabaa9c0d235a8dd0003e

I can run these chain-specs with the polkadot binary directly. The issue only exists with polkadot-launch.

Edit: This happens when we launch live chains in our polkadot-launch config:

```
🧹 Resolving parachain id...
2021-11-01 03:37:08 Low open file descriptor limit configured for the process. Current value: 4096, recommended value: 10000.
2021-11-01 03:37:08 Building chain spec

Killing all processes...
```

**Comment by clangenb** [comment]
I think we might just accept the issue until we might need to launch the live-specs.

**Comment by brenzi** [comment]
not sure if this is even meant to work. Can you describe in detail what does not work? Does the Relay-Chain produce blocks? the parachain - guess not

**Comment by clangenb** [comment]
Edited some more info into the description.

We used to do this. What I mean; Even if we don't attach any parachains in the polkadot-launch config, it does not launch the relay-chain successfully. Hence, I think it's only related to the relaychain.

**Comment by clangenb** [comment]
Obsolete, we switched to zombienet a long time ago
