### ISSUE TITLE
add chain-specs for kusama and westend

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-parachain#48]
Chain-specs to be added:

With launch-runtime:
* launch-kusama (loaded from json, generated by kusama-fresh)
* launch-kusama-fresh (encointer-keys, encointer-root is not endowed)
* launch-kusama-local (encointer-keys, encointer-root is endowed)
* launch-kusama-local-dev (use well-known keys)

* launch-westend (loaded from json generated by westend-fresh)
* launch-westend-fresh  (encointer-keys, encointer-root is not endowed)
* launch-westend-local (encointer-keys, encointer-root is endowed)
* launch-westend-local-dev (wellknown keys)

@brenzi suggestions?

**Comment by brenzi** [comment]
agreed. should suffice for now

**Comment by brenzi** [comment]
westend paraid: 2103
kusama paraid: 2014
