### ISSUE TITLE
align-runtimes with statemine (incrementally)

### ISSUE THREAD

**Issue by clangenb** [encointer/encointer-parachain#63]
I thought this will be a minor thing. However, https://github.com/encointer/encointer-parachain/pull/61 does not produce parachain blocks; hence I will merge in the statemine upgrades incrementally and test block production with each pr.

- [x] apply trivial changes to reduce the diff and give better overview to subsequent changes. #64 
- [x] apply statemine xcm config (disable parachain-side teleport) #66
- [ ] add multisig/proxy pallet and benchmark them.

**Comment by brenzi** [comment]
proxy has been added to encointer-runtime, but not yet benchmarked. I'd only do the remaining steps for the encointer-runtime. not for the launch. Launch has been tested on westend. Let's leave it as-is

**Comment by brenzi** [comment]
benchmarking is covered elsewhere....
